---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs
    tag: 1.0.3

inputs:
  - name: pcf-pipelines
  - name: opsman-metadata
  - name: terraform-state

outputs:
  - name: terraform-state-output

run:
  path: pcf-pipelines/install-pcf/azure/tasks/create-infrastructure/task.sh

params:
  AZURE_SUBSCRIPTION_ID:
  AZURE_TENANT_ID:
  AZURE_CLIENT_ID:
  AZURE_CLIENT_SECRET:
  AZURE_REGION:
  AZURE_TERRAFORM_PREFIX:
  PCF_ERT_DOMAIN:
